Updated GitHub CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,79 +23,96 @@ on:
     - cron: '16 9 * * *' # once a day @ 9:16am UTC (2:16am PST)
     
 jobs:
-  macOS-13:
-    name: macOS 13 Ventura
-    runs-on: macos-13
+  macOS:
+    name: macOS
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
     - name: Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=macOS,name=Any Mac"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     # - name: Unit Tests
-    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=macOS"
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=macOS" | xcpretty && exit ${PIPESTATUS[0]}
 
   macCatalyst:
     name: macCatalyst
-    runs-on: macos-13
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
     - name: Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     # - name: Unit Tests
-    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=macOS,variant=Mac Catalyst"
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=macOS,variant=Mac Catalyst" | xcpretty && exit ${PIPESTATUS[0]}
 
   iOS:
     name: iOS
-    runs-on: macos-13 # this must be macos, GitHub does not offer iOS directly but we can use xcodebuild
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
-    - name: iPhone 15 Simulator - Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=iOS Simulator,name=Any iOS Device"
-    # - name: iPhone 15 Simulator - Unit Tests
-    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=iOS Simulator,name=iPhone 15"
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Build
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=iOS Simulator,name=Any iOS Device" | xcpretty && exit ${PIPESTATUS[0]}
+    # - name: Unit Tests
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=iOS Simulator,name=iPhone 15" | xcpretty && exit ${PIPESTATUS[0]}
 
   tvOS:
     name: tvOS
-    runs-on: macos-13 # this must be macos, GitHub does not offer tvOS directly but we can use xcodebuild
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
-    - name: Apple TV - Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=tvOS Simulator,name=Any tvOS Simulator Device"
-    # - name: Apple TV - Unit Tests
-    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation)"
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Build
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=tvOS Simulator,name=Any tvOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
+    # - name: Unit Tests
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" | xcpretty && exit ${PIPESTATUS[0]}
 
   watchOS:
     name: watchOS
-    runs-on: macos-13 # this must be macos, GitHub does not offer watchOS directly but we can use xcodebuild
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
-    - name: Apple Watch - Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=watchOS Simulator,name=Any watchOS Simulator Device"
-    # - name: Apple Watch - Unit Tests
-    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)"
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Build
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=watchOS Simulator,name=Any watchOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
+    # - name: Unit Tests
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)" | xcpretty && exit ${PIPESTATUS[0]}
 
   demo-iOS:
     name: Demo Project (iOS)
-    runs-on: macos-13
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
-    - name: Select Xcode version
-      run: sudo xcode-select -s "/Applications/Xcode_15.0.app"
-    - name: Demo - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Demo/Demo.xcodeproj" -resolvePackageDependencies
-    - name: Demo - Build
-      run: xcodebuild build -project "Demo/Demo.xcodeproj" -scheme "Demo" -destination "platform=iOS Simulator,name=iPhone 15"
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Demo/Demo.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Build
+      run: xcodebuild build -project "Demo/Demo.xcodeproj" -scheme "Demo" -destination "platform=iOS Simulator,name=iPhone 15" | xcpretty && exit ${PIPESTATUS[0]}
 
   demo-macOS:
     name: Demo Project (macOS)
-    runs-on: macos-13
+    runs-on: macos-latest
     steps:
     - uses: actions/checkout@main
-    - name: Select Xcode version
-      run: sudo xcode-select -s "/Applications/Xcode_15.0.app"
-    - name: Demo - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Demo/Demo.xcodeproj" -resolvePackageDependencies
-    - name: Demo - Build
-      run: xcodebuild build -project "Demo/Demo.xcodeproj" -scheme "Demo" -destination "generic/platform=macOS,name=Any Mac"
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
+    - name: Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Demo/Demo.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
+    - name: Build
+      run: xcodebuild build -project "Demo/Demo.xcodeproj" -scheme "Demo" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
 
 # xcodebuild test reference:
 # https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/08-automation.html
